### ISSUE TITLE
 Questions about 3-phase-3-dockerfile-asts 

### ISSUE THREAD

**Issue by jhshz520** [jjhenkel/binnacle-icse2020#1] opened 2021-09-02 02:00 UTC
# Hi， I have some problems，and want to get your help
my os is ubuntu:16.04 ,and docker version  is 19.03
according to the datasets readme ,in 3-phase-3-dockerfile-asts phase,first I save the origin dataset, then I did ./generate.sh ,the gold.jsonl.xz was re-generated,but it was different  from  the origin file ，such as the use the commandline 
cat gold.jsonl.xz \
  | xz -cd \
  | grep '0317161148e8520e89b3b8e508f1772876bb67b6' \
  | jq,

# the new result is
![new](https://user-images.githubusercontent.com/29908692/131768511-defde949-44e3-4763-b119-65b7aef3d61d.png)
# the orgin result is
![origin](https://user-images.githubusercontent.com/29908692/131768529-f880efce-5f37-4d0f-8673-d6c1006af115.png)

the BASH-AND-MEM will be parsed UNKNOWN，I donot know where is the wrong ，Could you give me some help，Thansk a lot。

**Comment by jjhenkel** [comment] 2021-10-18 16:50
Sorry for the very delayed reply: was finishing up an internship / getting situated back at my University this fall. I've been trying to replicate this, but I can't --- I ran `./generate.sh` in `./datasets/3-phase-3-dockerfile-asts` and I do, indeed, end up with your second image. In the first image, from what I can tell, none of the "nested parsers" ran. Those produce the `SC-*` nodes that "enrich" the AST and make rule mining feasible. 

Have you made any progress since posting? I'd recommend trying on a different machine, if at all possible, to see if that helps. I run this on a CentOS workstation with Docker installed. I've also done this successfully on a less powerful Ubuntu desktop.

**Comment by jjhenkel** [comment] 2021-10-18 16:51
Oh, I see you're on Ubuntu. That's odd, I haven't encountered any issues there myself. Did you get any output during the generation that may give a hint as to what went wrong?

**Comment by jjhenkel** [comment] 2021-10-18 16:56
One debug step to try, this command would run the `enrich` script on a single AST (the one in the image---this assumes you're in the `./datasets/3-phase-3-dockerfile-asts` dir):

```bash
cat ../2-phase-2-dockerfile-asts/gold.jsonl.xz \
  | xz -cd \
  | grep '031716' \
  | docker run -i \
      --entrypoint='node' \
      binnacle/artifact:generate-phase-3 /build/app.js \
  | jq
```
This should be fast to run and (maybe, hopefully) produce debug output if something goes wrong. (The `./generate.sh` script runs against _all_ the data, this is what it's doing to each single file.)

**Comment by Zwlin98** [comment] 2022-03-18 08:36
I also encountered the same problem, and finally found that it was caused by the dependency change of the third phase program, and I submitted a PR to solve this problem.

**Comment by jjhenkel** [comment] 2022-03-19 00:44
Thanks you @Zwlin98 ! Your pull request has been merged. I'm going to close this issue now.

**Closed as completed by jjhenkel** 2022-03-19 00:44 UTC
